# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
jobs:
  include:
  - r: release
    before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github()'
      skip_cleanup: true
  - r: devel
  - r: oldrel
  - r: 3.4

os: linux
cache: packages

before_install:
  - Rscript -e 'install.packages("remotes")'

after_success:
  - Rscript -e 'covr::codecov()'
