# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
jobs:
  include:
  - r: release
  - r: devel
  - r: oldrel
  - r: 3.4


sudo: false
cache: packages
warnings_are_errors: false

r_github_packages:
  - rstudio/gt

after_success:
  - Rscript -e 'covr::codecov()'
